version: '3'
services:
  dev:
    image: openresty/openresty:1.21.4.1-0-focal
    entrypoint: /bin/bash

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../:/workspace:cached
      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      # - /var/run/docker.sock:/var/run/docker.sock
      # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
      # cap_add:
      #   - SYS_PTRACE
      # security_opt:
      #   - seccomp:unconfined

      # Overrides default command so things don't shut down after the process ends.
    command: -c "while sleep 1000; do :; done"
    environment:
      - LC_ALL=C
      - LANG=C
      - OPM_PUBLISH_TOKEN=xxxx
