name: Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
      - name: Install git
        run: apt-get update && apt-get install -y git
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Fix for issue brought up here: https://github.com/actions/checkout/issues/1169
      - name: Git config workaround
        run: git config --global --add safe.directory /__w/lua-resty-aws-signature/lua-resty-aws-signature
      - name: Setup SVU
        id: svu
        uses: obfu5c8/action-svu@v1.0.0
        with:
          strip-prefix: true
          svu-version: 2.2.0
      - name: Create git tag
        run: git tag ${{ steps.svu.outputs.version }}
      - name: Push tag to origin
        run: git push origin ${{ steps.svu.outputs.version }}
  # We call release directly, because Github actions can't chain
  # IE, the tag being created above *won't* trigger the on_tag.yaml file
  release:
    uses: ./.github/workflows/release.yaml
