name: Merge

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/release.yaml
    with:
      OPM_PUBLISH_TOKEN: ${{ secrets.OPM_PUBLISH_TOKEN }}
